apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'demoo'
spec:
  project: default
  source:
    repoURL: 'https://github.com/divyanshudaffodil/argocd.git'
    path: 'config'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
